package edu.upvictoria.fpoo;

/**
 * Parser class
 * The Parser class is responsible for parsing the tokens generated by the Lexer
 * class and interpreting the XML file.
  */
public class Parser {
    
}
