package edu.upvictoria.fpoo.XML_Parser;

/**
 * Interpreter class
 * 
 * The Interpreter class is responsible for interpreting the XML file.
 * It will use the tokens generated by the Lexer class and the Parser class to 
 * manage the rules of the XML file.
  */
public class XMLInterpreter {
    
}
