package edu.upvictoria.fpoo.XML_Parser;

import java.util.ArrayList;

/**
 * Parser class
 * The Parser class is responsible for parsing the tokens generated by the Lexer
 * class and interpreting the XML file.
  */
public class XMLParser {
  private ArrayList<Token> tokens;

  XMLParser(ArrayList<Token> tokens) {
    this.tokens = tokens;
  }

  public void parse() {
    
  }

}
